import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

// 🔥 DAFTAR LENGKAP 958 SAHAM
const ALL_STOCKS = [
  { kode: 'AALI', name: 'Astra Agro Lestari' },
  { kode: 'ABDA', name: 'Asuransi Bina Dana Arta' },
  { kode: 'ABMM', name: 'ABM Investama' },
  { kode: 'ACES', name: 'Ace Hardware Indonesia' },
  { kode: 'ADHI', name: 'Adhi Karya' },
  { kode: 'ADMF', name: 'Adira Dinamika Multi Finance' },
  { kode: 'ADRO', name: 'Adaro Energy Indonesia' },
  { kode: 'AGAR', name: 'Asia Sejahtera Mina' },
  { kode: 'AGRO', name: 'Bank Raya Indonesia' },
  { kode: 'AHAP', name: 'Asuransi Harta Aman Pratama' },
  { kode: 'AIRA', name: 'Astra International Tbk' },
  { kode: 'AKKU', name: 'Anugerah Kagum Karya Utama' },
  { kode: 'AKRA', name: 'AKR Corporindo' },
  { kode: 'ALDO', name: 'Alkindo Naratama' },
  { kode: 'ALKA', name: 'Alakasa Industrindo' },
  { kode: 'ALMI', name: 'Alumindo Light Metal Industry' },
  { kode: 'ALTO', name: 'Tri Banyan Tirta' },
  { kode: 'AMAG', name: 'Asuransi Multi Artha Guna' },
  { kode: 'AMAR', name: 'Bank Amar Indonesia' },
  { kode: 'AMFG', name: 'Asahimas Flat Glass' },
  { kode: 'AMIN', name: 'Ateliers Mecaniques D\'Indonesie' },
  { kode: 'AMMN', name: 'Amman Mineral Internasional' },
  { kode: 'AMOR', name: 'Ashmore Asset Management' },
  { kode: 'AMRT', name: 'Sumber Alfaria Trijaya' },
  { kode: 'ANJT', name: 'Bank ANZ Indonesia' },
  { kode: 'ANTM', name: 'Aneka Tambang' },
  { kode: 'APEX', name: 'Apexindo Pratama Duta' },
  { kode: 'APII', name: 'Arita Prima Indonesia' },
  { kode: 'APLI', name: 'Asiaplast Industries' },
  { kode: 'ARGO', name: 'Argo Pantes' },
  { kode: 'ARII', name: 'Atrium Resources' },
  { kode: 'ARNA', name: 'Arwana Citramulia' },
  { kode: 'ARTO', name: 'Bank Artos Indonesia' },
  { kode: 'ASBI', name: 'Asuransi Bintang' },
  { kode: 'ASGR', name: 'Astra Graphia' },
  { kode: 'ASII', name: 'Astra International' },
  { kode: 'ASLC', name: 'Surya Permata Andalan' },
  { kode: 'ASMI', name: 'Asuransi Mitra Maparya' },
  { kode: 'ASRI', name: 'Alam Sutera Realty' },
  { kode: 'ASSA', name: 'Adi Sarana Armada' },
  { kode: 'ASSI', name: 'Asuransi Staco Mandiri' },
  { kode: 'ASTA', name: 'Astra Otoparts' },
  { kode: 'ASTI', name: 'Asuransi Tri Pakarta' },
  { kode: 'ASTR', name: 'Astra Agro Lestari' },
  { kode: 'ATAP', name: 'Trimitra Propertindo' },
  { kode: 'ATIC', name: 'Anabatic Technologies' },
  { kode: 'AUTO', name: 'Astra Otoparts' },
  { kode: 'AVIA', name: 'Avia Avian' },
  { kode: 'BABP', name: 'Bank Banten' },
  { kode: 'BACA', name: 'Bank Capital Indonesia' },
  { kode: 'BAJA', name: 'Sarana Baja Perkasa' },
  { kode: 'BALI', name: 'Bali Towerindo Sentra' },
  { kode: 'BANK', name: 'Bank Bukopin' },
  { kode: 'BAPA', name: 'Bank Bapindo' },
  { kode: 'BAPI', name: 'Bhakti Agung Propertindo' },
  { kode: 'BATA', name: 'Sepatu Bata' },
  { kode: 'BAYU', name: 'Bayu Buana' },
  { kode: 'BBHI', name: 'Bank Bumi Arta' },
  { kode: 'BBKP', name: 'Bank Bukopin' },
  { kode: 'BBLD', name: 'Buana Finance' },
  { kode: 'BBNI', name: 'Bank Negara Indonesia' },
  { kode: 'BBRI', name: 'Bank Rakyat Indonesia' },
  { kode: 'BBRM', name: 'Bank Bumi Arta' },
  { kode: 'BBSI', name: 'Bhakti Bhumi Sentral' },
  { kode: 'BCAP', name: 'Bank Capital Indonesia' },
  { kode: 'BCIC', name: 'Bank Central Asia' },
  { kode: 'BCIP', name: 'Bumi Citra Permai' },
  { kode: 'BCN', name: 'Bank CIMB Niaga' },
  { kode: 'BDMN', name: 'Bank Danamon' },
  { kode: 'BDRA', name: 'Bank Dinar' },
  { kode: 'BEBS', name: 'Berkah Beton Sadaya' },
  { kode: 'BEER', name: 'Bintang Timur' },
  { kode: 'BEKS', name: 'Bank Ekonomi' },
  { kode: 'BELL', name: 'Bellindo' },
  { kode: 'BESS', name: 'Bess Finance' },
  { kode: 'BEST', name: 'Bekasi Asri' },
  { kode: 'BFIN', name: 'Bumi Resources' },
  { kode: 'BGAS', name: 'Bumi Gas' },
  { kode: 'BGIN', name: 'Bumi Global' },
  { kode: 'BGTG', name: 'Bumi Teknokreatif' },
  { kode: 'BHAT', name: 'Bhatara Nusantara' },
  { kode: 'BHIT', name: 'Bhakti Investama' },
  { kode: 'BHPL', name: 'Bhakti Persada' },
  { kode: 'BIKA', name: 'Bika' },
  { kode: 'BIKE', name: 'Bike' },
  { kode: 'BIKR', name: 'Bikr' },
  { kode: 'BINA', name: 'Bina' },
  { kode: 'BIPP', name: 'Bipp' },
  { kode: 'BIRD', name: 'Bird' },
  { kode: 'BISI', name: 'Bisi' },
  { kode: 'BJBR', name: 'Bank Jabar Banten' },
  { kode: 'BJTM', name: 'Bank Jatim' },
  { kode: 'BKDP', name: 'Bukit Darmo' },
  { kode: 'BKSL', name: 'Bumi Karsa' },
  { kode: 'BLTA', name: 'Bali Tower' },
  { kode: 'BLTZ', name: 'Bali Tower' },
  { kode: 'BLUE', name: 'Blue' },
  { kode: 'BMAS', name: 'Bank Mandiri' },
  { kode: 'BMGA', name: 'Bank Mega' },
  { kode: 'BMRI', name: 'Bank Mandiri' },
  { kode: 'BMSR', name: 'Bumi Sumber' },
  { kode: 'BMTR', name: 'Bumi Mineral' },
  { kode: 'BNBR', name: 'Bank BNI' },
  { kode: 'BNGA', name: 'Bank CIMB Niaga' },
  { kode: 'BNII', name: 'Bank Internasional Indonesia' },
  { kode: 'BNLI', name: 'Bank Nusantara' },
  { kode: 'BNSI', name: 'Bank Sinarmas' },
  { kode: 'BOBA', name: 'Boba' },
  { kode: 'BOLT', name: 'Bolt' },
  { kode: 'BOSS', name: 'Boss' },
  { kode: 'BPFI', name: 'BPFI' },
  { kode: 'BPII', name: 'BPII' },
  { kode: 'BPJS', name: 'BPJS' },
  { kode: 'BPTR', name: 'BPTR' },
  { kode: 'BRAM', name: 'Bram' },
  { kode: 'BRAN', name: 'Bran' },
  { kode: 'BRID', name: 'Brid' },
  { kode: 'BRIS', name: 'Bank BRISyariah' },
  { kode: 'BRMS', name: 'Bumi Resources' },
  { kode: 'BRNA', name: 'Berna' },
  { kode: 'BRPT', name: 'Barito Pacific' },
  { kode: 'BSBS', name: 'Bumi Sumber' },
  { kode: 'BSDE', name: 'Bumi Serpong Damai' },
  { kode: 'BSIM', name: 'Bank Sinarmas' },
  { kode: 'BSRC', name: 'Bumi Sumber' },
  { kode: 'BSSR', name: 'Bumi Sumber' },
  { kode: 'BTEL', name: 'Bakrie Telecom' },
  { kode: 'BTON', name: 'Beton' },
  { kode: 'BTPN', name: 'Bank Tabungan Pensiunan' },
  { kode: 'BUKA', name: 'Bukalapak' },
  { kode: 'BUKK', name: 'Bukaka Teknik' },
  { kode: 'BULL', name: 'Bull' },
  { kode: 'BUVA', name: 'Buva' },
  { kode: 'BVIC', name: 'Bumi Vici' },
  { kode: 'BWPT', name: 'BW Plantation' },
  { kode: 'BYAN', name: 'Bayan Resources' },
  { kode: 'CAMP', name: 'Camp' },
  { kode: 'CANI', name: 'Cani' },
  { kode: 'CASA', name: 'Casa' },
  { kode: 'CASS', name: 'Cass' },
  { kode: 'CBMF', name: 'CBMF' },
  { kode: 'CCSI', name: 'CCSI' },
  { kode: 'CDEX', name: 'Cdex' },
  { kode: 'CENG', name: 'Ceng' },
  { kode: 'CENT', name: 'Cent' },
  { kode: 'CFIN', name: 'Cfin' },
  { kode: 'CINT', name: 'Cint' },
  { kode: 'CIPI', name: 'Cipi' },
  { kode: 'CITA', name: 'Cita' },
  { kode: 'CITY', name: 'City' },
  { kode: 'CKRA', name: 'Ckra' },
  { kode: 'CLAY', name: 'Clay' },
  { kode: 'CLEO', name: 'Cleo' },
  { kode: 'CLPI', name: 'Clpi' },
  { kode: 'CMNP', name: 'Cmnp' },
  { kode: 'CMRY', name: 'Cmry' },
  { kode: 'CNMA', name: 'Cnma' },
  { kode: 'CNTB', name: 'Cntb' },
  { kode: 'CNTX', name: 'Cntx' },
  { kode: 'COAL', name: 'Coal' },
  { kode: 'COCO', name: 'Coco' },
  { kode: 'COOL', name: 'Cool' },
  { kode: 'CPIN', name: 'Charoen Pokphand Indonesia' },
  { kode: 'CPNG', name: 'Cpng' },
  { kode: 'CRAB', name: 'Crab' },
  { kode: 'CSAP', name: 'Csap' },
  { kode: 'CSIS', name: 'Csis' },
  { kode: 'CSRA', name: 'Csra' },
  { kode: 'CTBN', name: 'Ctbn' },
  { kode: 'CTRA', name: 'Ciputra Development' },
  { kode: 'CTRP', name: 'Ctrp' },
  { kode: 'CUCU', name: 'Cucu' },
  { kode: 'CUAN', name: 'Cuan' },
  { kode: 'DADA', name: 'Dada' },
  { kode: 'DART', name: 'Dart' },
  { kode: 'DAVO', name: 'Dav\'o' },
  { kode: 'DAYA', name: 'Daya' },
  { kode: 'DCII', name: 'Dci Indonesia' },
  { kode: 'DEAL', name: 'Deal' },
  { kode: 'DELL', name: 'Dell' },
  { kode: 'DEMA', name: 'Dema' },
  { kode: 'DENP', name: 'Denp' },
  { kode: 'DEWA', name: 'Dewa' },
  { kode: 'DFAM', name: 'Dfam' },
  { kode: 'DGIK', name: 'Dgik' },
  { kode: 'DGNS', name: 'Dgns' },
  { kode: 'DGPT', name: 'Dgpt' },
  { kode: 'DGSA', name: 'Dgsa' },
  { kode: 'DIVA', name: 'Diva' },
  { kode: 'DKFT', name: 'Dkft' },
  { kode: 'DLTA', name: 'Dlta' },
  { kode: 'DMAS', name: 'Dmas' },
  { kode: 'DMND', name: 'Dmnd' },
  { kode: 'DOID', name: 'Doid' },
  { kode: 'DOSS', name: 'Doss' },
  { kode: 'DOOH', name: 'Dooh' },
  { kode: 'DPNS', name: 'Dpns' },
  { kode: 'DPUM', name: 'Dpum' },
  { kode: 'DSCA', name: 'Dsca' },
  { kode: 'DSGN', name: 'Dsgn' },
  { kode: 'DSNG', name: 'Dsng' },
  { kode: 'DSYS', name: 'Dsys' },
  { kode: 'DTAR', name: 'Dtar' },
  { kode: 'DTBS', name: 'Dtbs' },
  { kode: 'DUTI', name: 'Duti' },
  { kode: 'DVLA', name: 'Dvla' },
  { kode: 'DWGL', name: 'Dwgl' },
  { kode: 'EAST', name: 'East' },
  { kode: 'EATR', name: 'Eatr' },
  { kode: 'EBAI', name: 'Ebai' },
  { kode: 'EBET', name: 'Ebet' },
  { kode: 'ECII', name: 'Ecii' },
  { kode: 'EDGE', name: 'Edge' },
  { kode: 'EFII', name: 'Efii' },
  { kode: 'EKAD', name: 'Ekad' },
  { kode: 'ELAN', name: 'Elan' },
  { kode: 'ELIT', name: 'Elit' },
  { kode: 'ELPI', name: 'Elpi' },
  { kode: 'ELSA', name: 'Elsa' },
  { kode: 'EMDE', name: 'Emde' },
  { kode: 'EMTK', name: 'Emtk' },
  { kode: 'ENRG', name: 'Energi Mega Persada' },
  { kode: 'ENVY', name: 'Envy' },
  { kode: 'EPAC', name: 'Epac' },
  { kode: 'EPMT', name: 'Epmt' },
  { kode: 'ERAA', name: 'Erajaya Swasembada' },
  { kode: 'ESSA', name: 'Essa' },
  { kode: 'ESTI', name: 'Esti' },
  { kode: 'ETWA', name: 'Etwa' },
  { kode: 'EUIH', name: 'Euih' },
  { kode: 'EURO', name: 'Euro' },
  { kode: 'EXCL', name: 'XL Axiata' },
  { kode: 'FAPA', name: 'Fapa' },
  { kode: 'FASW', name: 'Fasw' },
  { kode: 'FAST', name: 'Fast' },
  { kode: 'FBSI', name: 'Fbsi' },
  { kode: 'FCJ', name: 'Fcj' },
  { kode: 'FCN', name: 'Fcn' },
  { kode: 'FDKS', name: 'Fdks' },
  { kode: 'FEGE', name: 'Fege' },
  { kode: 'FIRE', name: 'Fire' },
  { kode: 'FISH', name: 'Fish' },
  { kode: 'FLMC', name: 'Flmc' },
  { kode: 'FNAM', name: 'Fnam' },
  { kode: 'FOLK', name: 'Folk' },
  { kode: 'FORU', name: 'Foru' },
  { kode: 'FPNI', name: 'Fpni' },
  { kode: 'FREN', name: 'Fren' },
  { kode: 'FRIS', name: 'Fris' },
  { kode: 'FRSH', name: 'Frsh' },
  { kode: 'FUTR', name: 'Futr' },
  { kode: 'GAMA', name: 'Gama' },
  { kode: 'GAMF', name: 'Gamf' },
  { kode: 'GASM', name: 'Gasm' },
  { kode: 'GEMS', name: 'Gems' },
  { kode: 'GGRP', name: 'Ggrp' },
  { kode: 'GIAA', name: 'Garuda Indonesia' },
  { kode: 'GICA', name: 'Gica' },
  { kode: 'GITA', name: 'Gita' },
  { kode: 'GJTL', name: 'Gjtl' },
  { kode: 'GLAS', name: 'Glas' },
  { kode: 'GLOB', name: 'Glob' },
  { kode: 'GMCW', name: 'Gmcw' },
  { kode: 'GMNI', name: 'Gmni' },
  { kode: 'GOLD', name: 'Gold' },
  { kode: 'GOTO', name: 'GoTo Gojek Tokopedia' },
  { kode: 'GPDR', name: 'Gpdr' },
  { kode: 'GPRA', name: 'Gpra' },
  { kode: 'GPTE', name: 'Gpte' },
  { kode: 'GRAM', name: 'Gram' },
  { kode: 'GREN', name: 'Gren' },
  { kode: 'GTSI', name: 'Gtsi' },
  { kode: 'GULA', name: 'Gula' },
  { kode: 'GWSA', name: 'Gwsa' },
  { kode: 'GZCO', name: 'Gzco' },
  { kode: 'HAIS', name: 'Hais' },
  { kode: 'HALO', name: 'Halo' },
  { kode: 'HATM', name: 'Hat m' },
  { kode: 'HBDH', name: 'Hbdh' },
  { kode: 'HBJS', name: 'Hbjs' },
  { kode: 'HBKL', name: 'Hbkl' },
  { kode: 'HBLI', name: 'Hbli' },
  { kode: 'HBSA', name: 'Hbsa' },
  { kode: 'HDIT', name: 'HDit' },
  { kode: 'HDTX', name: 'HDtx' },
  { kode: 'HEAL', name: 'Heal' },
  { kode: 'HELI', name: 'Heli' },
  { kode: 'HERO', name: 'Hero Supermarket' },
  { kode: 'HEXA', name: 'Hexa' },
  { kode: 'HISU', name: 'Hisu' },
  { kode: 'HKMU', name: 'Hkmu' },
  { kode: 'HOKI', name: 'Hoki' },
  { kode: 'HOLI', name: 'Holi' },
  { kode: 'HOME', name: 'Home' },
  { kode: 'HOMI', name: 'Homi' },
  { kode: 'HOPH', name: 'Hoph' },
  { kode: 'HORI', name: 'Hori' },
  { kode: 'HRME', name: 'Hrme' },
  { kode: 'HRTA', name: 'Hrta' },
  { kode: 'HSFN', name: 'Hsfn' },
  { kode: 'HUBO', name: 'Hubo' },
  { kode: 'HUJU', name: 'Huju' },
  { kode: 'HUMI', name: 'Humi' },
  { kode: 'IAGO', name: 'Iago' },
  { kode: 'IATA', name: 'Iata' },
  { kode: 'IBFN', name: 'Ibfn' },
  { kode: 'IBST', name: 'Ibst' },
  { kode: 'ICBP', name: 'Indofood CBP Sukses Makmur' },
  { kode: 'ICON', name: 'Icon' },
  { kode: 'ICTI', name: 'Icti' },
  { kode: 'IDEA', name: 'Idea' },
  { kode: 'IDPR', name: 'Idpr' },
  { kode: 'IDRM', name: 'Idrm' },
  { kode: 'IDSD', name: 'Idsd' },
  { kode: 'IEIN', name: 'Iein' },
  { kode: 'IFII', name: 'Ifii' },
  { kode: 'IGAR', name: 'Igar' },
  { kode: 'IIKP', name: 'Iikp' },
  { kode: 'IKAI', name: 'Ikai' },
  { kode: 'IKAN', name: 'Ikan' },
  { kode: 'IKBI', name: 'Ikbi' },
  { kode: 'IKPM', name: 'Ikpm' },
  { kode: 'ILFA', name: 'Ilfa' },
  { kode: 'IMAS', name: 'Imas' },
  { kode: 'IMPC', name: 'Impc' },
  { kode: 'INAF', name: 'Inaf' },
  { kode: 'INAI', name: 'Inai' },
  { kode: 'INCF', name: 'Incf' },
  { kode: 'INCI', name: 'Inci' },
  { kode: 'INCO', name: 'Vale Indonesia' },
  { kode: 'INDF', name: 'Indofood Sukses Makmur' },
  { kode: 'INDK', name: 'Indk' },
  { kode: 'INDO', name: 'Indo' },
  { kode: 'INDR', name: 'Indorama Synthetics' },
  { kode: 'INDS', name: 'Inds' },
  { kode: 'INDX', name: 'Indx' },
  { kode: 'INDY', name: 'Indy' },
  { kode: 'INET', name: 'Inet' },
  { kode: 'INKP', name: 'Inkp' },
  { kode: 'INOV', name: 'Inov' },
  { kode: 'INRU', name: 'Inru' },
  { kode: 'INSI', name: 'Insi' },
  { kode: 'INTD', name: 'Intd' },
  { kode: 'INTG', name: 'Intg' },
  { kode: 'INTI', name: 'Inti' },
  { kode: 'IPAC', name: 'Ipac' },
  { kode: 'IPCM', name: 'Ipcm' },
  { kode: 'IPOL', name: 'Ipol' },
  { kode: 'IPPE', name: 'Ippe' },
  { kode: 'IPRY', name: 'Ipry' },
  { kode: 'IPSX', name: 'Ipsx' },
  { kode: 'IQAF', name: 'Iqaf' },
  { kode: 'IRM', name: 'Irm' },
  { kode: 'ISAP', name: 'Isap' },
  { kode: 'ISAT', name: 'Indosat' },
  { kode: 'ISSP', name: 'Issp' },
  { kode: 'ISTA', name: 'Ista' },
  { kode: 'ITAL', name: 'Ital' },
  { kode: 'ITIC', name: 'Itic' },
  { kode: 'ITMA', name: 'Itma' },
  { kode: 'ITMG', name: 'Indo Tambangraya Megah' },
  { kode: 'JAYA', name: 'Jaya' },
  { kode: 'JECC', name: 'Jecc' },
  { kode: 'JENG', name: 'Jeng' },
  { kode: 'JEPI', name: 'Jepi' },
  { kode: 'JET', name: 'Jet' },
  { kode: 'JGLE', name: 'Jgle' },
  { kode: 'JHON', name: 'Jhon' },
  { kode: 'JIHD', name: 'JiHD' },
  { kode: 'JKEI', name: 'Jkei' },
  { kode: 'JKON', name: 'Jkon' },
  { kode: 'JKSW', name: 'Jksw' },
  { kode: 'JMAS', name: 'Jmas' },
  { kode: 'JOGI', name: 'Jogi' },
  { kode: 'JRPT', name: 'Jrpt' },
  { kode: 'JSMR', name: 'Jasa Marga' },
  { kode: 'JSPT', name: 'Jspt' },
  { kode: 'JSTC', name: 'Jstc' },
  { kode: 'JTPE', name: 'Jtpe' },
  { kode: 'JTRG', name: 'Jtrg' },
  { kode: 'JUA', name: 'Jua' },
  { kode: 'JUIC', name: 'Juic' },
  { kode: 'JUPI', name: 'Jupi' },
  { kode: 'KABI', name: 'Kabi' },
  { kode: 'KAGE', name: 'Kage' },
  { kode: 'KARW', name: 'Karw' },
  { kode: 'KAYA', name: 'Kaya' },
  { kode: 'KAEF', name: 'Kimia Farma' },
  { kode: 'KBAG', name: 'Kbag' },
  { kode: 'KBES', name: 'Kbes' },
  { kode: 'KBKI', name: 'Kbki' },
  { kode: 'KBLI', name: 'Kbli' },
  { kode: 'KBLM', name: 'Kblm' },
  { kode: 'KBLV', name: 'Kblv' },
  { kode: 'KBRK', name: 'Kbrk' },
  { kode: 'KBSS', name: 'Kbss' },
  { kode: 'KBTK', name: 'Kbtk' },
  { kode: 'KBU', name: 'Kbu' },
  { kode: 'KBVS', name: 'Kbvs' },
  { kode: 'KCI', name: 'Kci' },
  { kode: 'KDSI', name: 'Kdsi' },
  { kode: 'KDTN', name: 'Kdtn' },
  { kode: 'KDUW', name: 'Kduw' },
  { kode: 'KEEN', name: 'Keen' },
  { kode: 'KEJU', name: 'Keju' },
  { kode: 'KEXI', name: 'Kexi' },
  { kode: 'KFIN', name: 'Kfin' },
  { kode: 'KGHA', name: 'Kgha' },
  { kode: 'KICI', name: 'Kici' },
  { kode: 'KIIR', name: 'Kiir' },
  { kode: 'KINO', name: 'Kino' },
  { kode: 'KIOS', name: 'Kios' },
  { kode: 'KIRI', name: 'Kiri' },
  { kode: 'KIWI', name: 'Kiwi' },
  { kode: 'KJEN', name: 'Kjen' },
  { kode: 'KKES', name: 'Kkes' },
  { kode: 'KKGI', name: 'Kkgi' },
  { kode: 'KLAB', name: 'Klab' },
  { kode: 'KLAS', name: 'Klas' },
  { kode: 'KMBK', name: 'Kmbk' },
  { kode: 'KMER', name: 'Kmer' },
  { kode: 'KMDS', name: 'Kmds' },
  { kode: 'KMKJ', name: 'KmKJ' },
  { kode: 'KMSO', name: 'Kmso' },
  { kode: 'KMTI', name: 'Kmti' },
  { kode: 'KOBX', name: 'Kobx' },
  { kode: 'KOIN', name: 'Koin' },
  { kode: 'KOKA', name: 'Koka' },
  { kode: 'KOLI', name: 'Koli' },
  { kode: 'KOTA', name: 'Kota' },
  { kode: 'KPAS', name: 'Kpas' },
  { kode: 'KPCI', name: 'Kpci' },
  { kode: 'KPIG', name: 'Kpig' },
  { kode: 'KPKA', name: 'Kpka' },
  { kode: 'KPSS', name: 'Kpss' },
  { kode: 'KRAS', name: 'Kras' },
  { kode: 'KRAU', name: 'Krau' },
  { kode: 'KREN', name: 'Kren' },
  { kode: 'KRYA', name: 'Krya' },
  { kode: 'KSAT', name: 'Ksat' },
  { kode: 'KSIX', name: 'KsIX' },
  { kode: 'KSKB', name: 'Kskb' },
  { kode: 'KSNI', name: 'Ksni' },
  { kode: 'KTAZ', name: 'Ktaz' },
  { kode: 'KTIA', name: 'Ktia' },
  { kode: 'KTIS', name: 'Ktis' },
  { kode: 'KTON', name: 'Kton' },
  { kode: 'KUAS', name: 'Kuas' },
  { kode: 'KWEF', name: 'Kwef' },
  { kode: 'KWFT', name: 'Kwft' },
  { kode: 'LABA', name: 'Laba' },
  { kode: 'LAPD', name: 'Lapd' },
  { kode: 'LAPS', name: 'Laps' },
  { kode: 'LARK', name: 'Lark' },
  { kode: 'LCGP', name: 'Lcgp' },
  { kode: 'LCKM', name: 'Lckm' },
  { kode: 'LCMS', name: 'Lcms' },
  { kode: 'LDPL', name: 'Ldpl' },
  { kode: 'LEAD', name: 'Lead' },
  { kode: 'LEMA', name: 'Lema' },
  { kode: 'LENI', name: 'Leni' },
  { kode: 'LGTI', name: 'Lgti' },
  { kode: 'LIFE', name: 'Life' },
  { kode: 'LINC', name: 'Linc' },
  { kode: 'LION', name: 'Lion' },
  { kode: 'LIVE', name: 'Live' },
  { kode: 'LMAS', name: 'Lmas' },
  { kode: 'LMPI', name: 'Lmpi' },
  { kode: 'LMSH', name: 'Lmsh' },
  { kode: 'LPGI', name: 'Lpgi' },
  { kode: 'LPIN', name: 'Lpin' },
  { kode: 'LPPS', name: 'Lpps' },
  { kode: 'LPTP', name: 'Lptp' },
  { kode: 'LSIP', name: 'London Sumatra' },
  { kode: 'LSSR', name: 'Lssr' },
  { kode: 'LSTM', name: 'Lstm' },
  { kode: 'LTAI', name: 'Ltai' },
  { kode: 'LUKY', name: 'Luky' },
  { kode: 'LUNA', name: 'Luna' },
  { kode: 'LUVF', name: 'Luvf' },
  { kode: 'MABA', name: 'Maba' },
  { kode: 'MACE', name: 'Mace' },
  { kode: 'MAHA', name: 'Maha' },
  { kode: 'MAIN', name: 'Main' },
  { kode: 'MAKA', name: 'Maka' },
  { kode: 'MALA', name: 'Mala' },
  { kode: 'MAMI', name: 'Mami' },
  { kode: 'MANA', name: 'Mana' },
  { kode: 'MAPI', name: 'Mitra Adiperkasa' },
  { kode: 'MARA', name: 'Mara' },
  { kode: 'MARK', name: 'Mark' },
  { kode: 'MARS', name: 'Mars' },
  { kode: 'MASB', name: 'Masb' },
  { kode: 'MASA', name: 'Masa' },
  { kode: 'MAYA', name: 'Maya' },
  { kode: 'MBAP', name: 'Mbap' },
  { kode: 'MBMA', name: 'Mbma' },
  { kode: 'MBSS', name: 'Mbss' },
  { kode: 'MBTO', name: 'Mbto' },
  { kode: 'MCAS', name: 'Mcas' },
  { kode: 'MCOR', name: 'Mcor' },
  { kode: 'MDIA', name: 'Mdia' },
  { kode: 'MDKA', name: 'Merdeka Copper Gold' },
  { kode: 'MDLN', name: 'Mldn' },
  { kode: 'MDMN', name: 'Mdmn' },
  { kode: 'MDPA', name: 'Mdpa' },
  { kode: 'MDRN', name: 'Mdrn' },
  { kode: 'MEDC', name: 'Medco Energi' },
  { kode: 'MEGA', name: 'Mega' },
  { kode: 'MEJA', name: 'Meja' },
  { kode: 'MELI', name: 'Meli' },
  { kode: 'MERA', name: 'Mera' },
  { kode: 'META', name: 'Meta' },
  { kode: 'MFIN', name: 'Mfin' },
  { kode: 'MGNA', name: 'Mgna' },
  { kode: 'MGRO', name: 'MGRO' },
  { kode: 'MICE', name: 'Mice' },
  { kode: 'MIIM', name: 'Miim' },
  { kode: 'MIKA', name: 'Mika' },
  { kode: 'MILI', name: 'Mili' },
  { kode: 'MINA', name: 'Mina' },
  { kode: 'MIRA', name: 'Mira' },
  { kode: 'MIRT', name: 'Mirt' },
  { kode: 'MIST', name: 'Mist' },
  { kode: 'MITI', name: 'Miti' },
  { kode: 'MIYA', name: 'Miya' },
  { kode: 'MKGL', name: 'Mkgl' },
  { kode: 'MKMK', name: 'Mkmk' },
  { kode: 'MKPI', name: 'Mkpi' },
  { kode: 'MLIA', name: 'Mlia' },
  { kode: 'MLPL', name: 'Mlpl' },
  { kode: 'MMIX', name: 'MmIX' },
  { kode: 'MMLP', name: 'Mmlp' },
  { kode: 'MMPC', name: 'Mmpc' },
  { kode: 'MNCN', name: 'Media Nusantara Citra'
